# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name : coverlet
      uses: b3b00/coverlet-action@1.2.5
      with:
        testProject: 'BTModMerger.Test/BTModMerger.Test.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[BTModMerger.Test]*'
    - name: coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{steps.coverlet.outputs.coverageFile}}
        parallel: true
