name: Release

on:
  workflow_dispatch:
    inputs:
      CurrentVersion:
        description: "Current version"
        required: true
        type: string
      PrevVersion:
        description: "Previous version"
        required: true
        type: string
      AllowUpdates:
        description: "Allow updating tag"
        type: boolean

env:
  PR_BODY: |
    [![Coverage Status](https://badge.coveralls.io/repos/github/DrizztDoUrden/BTModMerger/badge.svg?tag=${{ inputs.CurrentVersion }})](https://badge.coveralls.io/github/DrizztDoUrden/BTModMerger?tag=${{ inputs.CurrentVersion }}) [![CodeQL](https://github.com/DrizztDoUrden/BTModMerger/actions/workflows/codeql.yml/badge.svg?tag=${{ inputs.CurrentVersion }})](https://github.com/DrizztDoUrden/BTModMerger/actions/workflows/codeql.yml)
    ^ fix link here
    Don't forget to add some meaningful changelog
    Full Changelog: [${{ inputs.PrevVersion }}...${{ inputs.CurrentVersion }}](https://github.com/DrizztDoUrden/BTModMerger/compare/${{ inputs.PrevVersion }}...${{ inputs.CurrentVersion }})

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Publish --no-restore
      
    - name: Build for self-contained
      run: dotnet build --configuration PublishSC --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-restore

    - name: Publish Portable
      id: portable
      run: |
          dotnet publish --no-build BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/Portable.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.${{ inputs.CurrentVersion }}.zip BTModMerger/bin/publish/BTModManager

    - name: Publish Windows
      id: windows
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContained.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.self-contained.${{ inputs.CurrentVersion }}.zip BTModMerger/bin/publish/BTModManager.self-contained

    - name: Publish Linux
      id: linux
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContainedLinux.pubxml
          mkdir -p artifacts
          tar -czvf artifacts/BTModManager.self-contained.linux.${{ inputs.CurrentVersion }}.tar.gz BTModMerger/bin/publish/BTModManager.self-contained.linux

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.CurrentVersion }}
        artifacts: "artifacts/BTModManager.${{ inputs.CurrentVersion }}.zip,artifacts/BTModManager.self-contained.${{ inputs.CurrentVersion }}.zip,artifacts/BTModManager.self-contained.linux.${{ inputs.CurrentVersion }}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: ${{ inputs.AllowUpdates }}
        body: ${{ env.PR_BODY }}
        draft: true
        removeArtifacts: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
