name: Release

on:
  workflow_dispatch:
    inputs:
      VersionMajor:
        description: "Version: major"
        required: true
        type: number
      VersionMinor:
        description: "Version: minor"
        required: true
        type: number
      VersionPatch:
        description: "Version: patch"
        required: true
        type: number

env:
    CURRENT_VERSION: v${{ inputs.VersionMajor }}.${{ inputs.VersionMinor }}.${{ inputs.VersionPatch }}
    PREV_VERSION: v${{ inputs.VersionMajor }}.${{ inputs.VersionMinor }}.${{ inputs.VersionPatch - 1 }}
    PR_BODY: |
      [![Coverage Status](https://badge.coveralls.io/repos/github/DrizztDoUrden/BTModMerger/badge.svg?tag=${{ env.CURRENT_VERSION }})](https://badge.coveralls.io/github/DrizztDoUrden/BTModMerger?tag=${{ env.CURRENT_VERSION }}) [![CodeQL](https://github.com/DrizztDoUrden/BTModMerger/actions/workflows/codeql.yml/badge.svg?tag=${{ env.CURRENT_VERSION }})](https://github.com/DrizztDoUrden/BTModMerger/actions/workflows/codeql.yml)
      ^ fix link here
      V check prev version here
      Full Changelog: [${{ env.PREV_VERSION }}...${{ env.CURRENT_VERSION }}](https://github.com/DrizztDoUrden/BTModMerger/compare/${{ env.PREV_VERSION }}...${{ env.CURRENT_VERSION }})

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Publish --no-restore
      
    - name: Build for self-contained
      run: dotnet build --configuration PublishSC --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal

    - name: Publish Portable
      id: portable
      run: |
          dotnet publish --no-build BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/Portable.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.${{ env.CURRENT_VERSION }}".zip BTModMerger/bin/publish/BTModManager

    - name: Publish Windows
      id: windows
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContained.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.self-contained.${{ env.CURRENT_VERSION }}.zip BTModMerger/bin/publish/BTModManager.self-contained

    - name: Publish Linux
      id: linux
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContainedLinux.pubxml
          mkdir -p artifacts
          tar -czvf artifacts/BTModManager.self-contained.linux.${{ env.CURRENT_VERSION }}.tar.gz BTModMerger/bin/publish/BTModManager.self-contained.linux

    - uses: ncipollo/release-action@v1
      with:
        name: ${{ env.CURRENT_VERSION }}
        artifacts: "artifacts/BTModManager.${{ env.CURRENT_VERSION }}.zip,artifacts/BTModManager.self-contained.${{ env.CURRENT_VERSION }}.zip,artifacts/BTModManager.self-contained.linux.${{ env.CURRENT_VERSION }}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ env.CURRENT_VERSION }}
        body: ${{ env.PR_BODY }}
