name: Release

on:
  push:
    tags: ['v*.*.*']

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Publish --no-restore
      
    - name: Build for self-contained
      run: dotnet build --configuration PublishSC --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal

    - name: Publish Portable
      id: portable
      run: |
          dotnet publish --no-build BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/Portable.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.${RELEASE_VERSION}.zip BTModMerger/bin/publish/BTModManager

    - name: Publish Windows
      id: windows
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContained.pubxml
          mkdir -p artifacts
          zip -9 -qr artifacts/BTModManager.self-contained.${RELEASE_VERSION}.zip BTModMerger/bin/publish/BTModManager.self-contained

    - name: Publish Linux
      id: linux
      run: |
          dotnet publish BTModMerger -p:PublishProfile=BTModMerger/Properties/PublishProfiles/SelfContainedLinux.pubxml
          mkdir -p artifacts
          tar -czvf artifacts/BTModManager.self-contained.linux.${RELEASE_VERSION}.tar.gz BTModMerger/bin/publish/BTModManager.self-contained.linux

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: CreateRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false
        release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}

    - name: Upload portable artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.CreateRelease.outputs.upload_url }}
        asset_path: artifacts/BTModManager.zip
        asset_name: BTModManager.zip
        asset_content_type: application/zip

    - name: Upload Windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.CreateRelease.outputs.upload_url }}
        asset_path: artifacts/BTModManager.self-contained.zip
        asset_name: BTModManager.self-contained.zip
        asset_content_type: application/gzip

    - name: Upload Linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.CreateRelease.outputs.upload_url }}
        asset_path: artifacts/BTModManager.self-contained.linux.tar.gz
        asset_name: BTModManager.self-contained.linux.tar.gz    
        asset_content_type: application/zip
